### ISSUE TITLE
Serial Decode Error on Python3

### ISSUE THREAD

**Issue by stout762** [meuter/citizenshell#9]
Reading from the SerialShell under Python3 raises a TypeError, while it works correctly under Python 2.7.12

Platform: Ubuntu/Xenial64
Python Version: 3.5.2

When I run: python3 test_shell.py

The interpreter returns:

Traceback (most recent call last):
  File "test_shell.py", line 10, in <module>
    main()
  File "test_shell.py", line 4, in main
    shell = Shell("serial://root:nomad@/dev/ttyUSB1?baudrate=115200")
  File "/usr/local/lib/python3.5/dist-packages/citizenshell/shell.py", line 23, in Shell
    password=parsed_uri.password, baudrate=parsed_uri.baudrate, **parsed_uri.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/citizenshell/serialshell.py", line 23, in __init__
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/citizenshell/abstractremoteshell.py", line 22, in connect
    self.do_connect()
  File "/usr/local/lib/python3.5/dist-packages/citizenshell/serialshell.py", line 30, in do_connect
    out = self._read_available()
  File "/usr/local/lib/python3.5/dist-packages/citizenshell/serialshell.py", line 60, in _read_available
    out += self._serial.read(self._serial.in_waiting)
TypeError: Can't convert 'bytes' object to str implicitly

[test_serial_shell.txt](https://github.com/meuter/citizenshell/files/2386010/test_serial_shell.txt)

**Comment by meuter** [comment]
Thanks for the report. I'll take a look this week end.

**Comment by meuter** [comment]
Fixed in 2.2.1 (freshly uploaded on pypi). Feel free to reopen if you still encounter this issue.
